package Challenges;

public class EvenFib
{
    /*
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
     */



    public static void main(String[] args)
    {
        int pre = 1;
        int current = 1;
        int total = 0;

        while (pre < 4000000)
        {
            pre = pre + current;
            current = pre - current;

            if (pre % 2 == 0)
            {
                total += pre;
            }

            System.out.println(total);

        }
    }

}
